channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=23.1.2
- pip:
  - mlflow==2.4
  - botocore==1.29.76
  - cffi==1.15.1
  - defusedxml==0.7.1
  - dill==0.3.6
  - fsspec==2023.4.0
  - importlib-metadata==6.0.0
  - lz4==4.3.2
  - numpy==1.22.4
  - packaging==23.0
  - pandas==1.3.4
  - pathlib==1.0.1
  - pillow==9.4.0
  - protobuf==4.23.3
  - pydot==1.4.2
  - python-snappy==0.6.1
  - requests==2.29.0
  - scipy==1.10.1
  - tblib==1.7.0
  - tensorflow-intel==2.12.0
  - tensorflow==2.12.0
  - zstandard==0.19.0
name: mlflow-env
